use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "engram", about = "Plan-based agentic development helper")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Commands,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Initialize engram in this repository
    Init,
    /// Create a GitHub issue as a plan
    Plan {
        /// Issue title
        title: String,
        /// Issue body
        #[arg(long)]
        body: Option<String>,
    },
    /// Synthesize learnings from a closed issue+PR into memory
    Learn {
        /// GitHub issue number
        issue: Option<u64>,
        /// Process all closed plan issues that have not yet been learned
        #[arg(long, conflicts_with = "issue")]
        all: bool,
    },
    /// Check that all engram dependencies are installed and configured
    Doctor,
    /// List open engram-plan issues
    List,
    /// Learn from a closed issue+PR and close the issue
    Land {
        /// GitHub issue number
        issue: u64,
    },
    /// Show the linked engram issue and PR for the current branch
    Status,
    /// Prune and merge memory files that don't meet the future-looking standard
    Compact,
    /// Coordinate multiple related plans toward a shared goal
    Objective {
        #[command(subcommand)]
        subcommand: ObjectiveCommands,
    },
}

#[derive(Subcommand)]
pub enum ObjectiveCommands {
    /// Create a new objective with a roadmap of nodes
    New {
        /// Objective title
        title: String,
        /// Body with ## Goal and ## Roadmap (bullet list) sections
        #[arg(long)]
        body: String,
    },
    /// List open objective issues
    List,
    /// View an objective and its roadmap
    View {
        /// Objective issue number
        number: u64,
    },
    /// Create a plan issue for a specific objective node
    Plan {
        /// Objective issue number
        number: u64,
        /// Node ID (e.g. 1.1)
        #[arg(
            long,
            conflicts_with = "all_unblocked",
            required_unless_present = "all_unblocked"
        )]
        node: Option<String>,
        /// Create plan issues for all pending nodes whose dependencies are all done
        #[arg(long, conflicts_with = "node")]
        all_unblocked: bool,
        /// Plan body; generated by Claude if omitted
        #[arg(long)]
        body: Option<String>,
    },
    /// Synthesize learnings from all plans in an objective and close it when done
    Land {
        /// Objective issue number
        number: u64,
    },
}
